

FORBIDDEN = [
    {'SKLMultinomialNB', 'SKLNystroem'},
    {'SKLMultinomialNB', 'SKLKernelPCA'},
    {'SKLMultinomialNB', 'SKLFastICA'},
    {'SKLMultinomialNB', 'SKLPCA'},
    {'SKLMultinomialNB', 'SKLRBFSampler'},
    {'SKLGaussianNaiveBayes', 'SKLNystroem'},
    {'SKLGaussianNaiveBayes', 'SKLRBFSampler'},
    {'SKLGaussianNaiveBayes', 'SKLKernelPCA'},
    {'SKLRandomForest', 'SKLNystroem'},
    {'SKLRandomForest', 'SKLRBFSampler'},
    {'SKLRandomForest', 'SKLKernelPCA'},
    {'SKLKernelSVC', 'SKLNystroem'},
    {'SKLKernelSVC', 'SKLRBFSampler'},
    {'SKLKernelSVC', 'SKLKernelPCA'},
    {'SKLKNearestNeighbors', 'SKLNystroem'},
    {'SKLKNearestNeighbors', 'SKLRBFSampler'},
    {'SKLKNearestNeighbors', 'SKLKernelPCA'},
    {'SKLGradientBoosting', 'SKLNystroem'},
    {'SKLGradientBoosting', 'SKLRBFSampler'},
    {'SKLGradientBoosting', 'SKLKernelPCA'},
    {'SKLExtraTrees', 'SKLNystroem'},
    {'SKLExtraTrees', 'SKLRBFSampler'},
    {'SKLExtraTrees', 'SKLKernelPCA'},
    {'SKLDecisionTree', 'SKLNystroem'},
    {'SKLDecisionTree', 'SKLRBFSampler'},
    {'SKLDecisionTree', 'SKLKernelPCA'},
    {'SKLAdaBoost', 'SKLNystroem'},
    {'SKLAdaBoost', 'SKLRBFSampler'},
    {'SKLAdaBoost', 'SKLKernelPCA'},
    {'SKLMultinomialNB', 'SKLSelectRates'},
    {'SKLMultinomialNB', 'SKLSelectPercentile'},
    {'SKLQuadraticDiscriminantAnalysis', 'SKLRandomTreesEmbedding'},
    {'SKLLinearDiscriminantAnalysis', 'SKLRandomTreesEmbedding'},
    {'SKLGradientBoosting', 'SKLRandomTreesEmbedding'},
    {'SKLGaussianNaiveBayes', 'SKLRandomTreesEmbedding'},
    {'SKLMultinomialNB', 'SKLPolynomialFeatures'},
    {'SKLMultinomialNB', 'NoFeaturePreprocessor'},
    {'SKLMultinomialNB', 'SKLSelectFromLinearSVC'},
    {'SKLMultinomialNB', 'SKLFeatureAgglomeration'},
    {'SKLMultinomialNB', 'SKLSelectFromExtraTrees'}
]
